spring.application.name=asistencias

# URL de conexion a la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/asisttec?serverTimezone=UTC

# Credenciales de acceso
spring.datasource.username=root
spring.datasource.password=admin

# Configuración Hibernate / JPA
# ´update´ crea o actualiza las tablas automaticamente segun las clases de java
spring.jpa.hibernate.ddl-auto=validate

# Flyway ejecuta las migraciones automáticamente al arrancar
spring.flyway.enabled=true

# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Creación inicial del administrador
app.bootstrap-admin.enabled=${BOOTSTRAP_ADMIN_ENABLED:false}
app.bootstrap-admin.username=${BOOTSTRAP_ADMIN_USERNAME:}
app.bootstrap-admin.password=${BOOTSTRAP_ADMIN_PASSWORD:}

# JWT
app.jwt.secret=${JWT_SECRET:}
app.jwt.issuer=asistencias-api
app.jwt.expiration-minutes=30